SET DEFINE OFF;
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (1, 'PAGO NOMINA', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (2, 'COMIDA', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (3, 'ARRIENDO', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (10, 'PLATAFORMAS DIGITALES', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (13, 'TRANSFERENCIA ENTRE CUENTAS', TO_DATE('21/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (15, 'INTERESES', TO_DATE('31/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (16, 'AJUSTE CONTABLE', TO_DATE('31/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (17, 'MOTO', TO_DATE('2/04/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (14, 'DONACION', TO_DATE('24/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (4, 'AHORRO', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (5, 'TRANSPORTE', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (6, 'SALUD', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (7, 'VIAJES', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (8, 'ENTRETENIMIENTO', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (9, 'MASCOTA', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (11, 'INGRESO INICIAL CUENTA', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.CONCEPTOS_MOVIMIENTO
   (CODIGO, NOMBRE_CONCEPTO, FECHA_CREACION)
 Values
   (12, 'PRESTAMO', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
COMMIT;
