--
-- Create Schema Script
--   Database Version            : 21.0.0.0.0
--   Database Compatible Level   : 21.0.0
--   Script Compatible Level     : 21.0.0
--   Toad Version                : 12.11.0.95
--   DB Connect String           : LOCALHOST_XEPDB1
--   Schema                      : CONTABILIDAD
--   Script Created by           : CONTABILIDAD
--   Script Created at           : 2/04/2023 5:06:56 p. m.
--   Notes                       : 
--

-- Object Counts: 
--   Roles: 2           System Privileges: 241  Roles: 19           Grants: 250 
--   Users: 1           System Privileges: 1    Roles: 2                 
--   Tablespaces: 2     Datafiles: 1        Tempfiles: 1 
-- 
--   Functions: 1       Lines of Code: 43 
--   Indexes: 6         Columns: 9          
--   Sequences: 5 
--   Tables: 5          Columns: 22         Constraints: 9      
--   Triggers: 1 
--   Views: 2           Columns: 5          


-- "Set define off" turns off substitution variables.
Set define off; 

--
-- USERS  (Tablespace) 
--
CREATE TABLESPACE USERS DATAFILE 
  'C:\APP\DANIELFRANCO\PRODUCT\21C\ORADATA\XE\XEPDB1\USERS01.DBF' SIZE 5M AUTOEXTEND ON NEXT 1280K MAXSIZE UNLIMITED
LOGGING
DEFAULT 
  NO INMEMORY
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--
-- TEMP  (Tablespace) 
--
CREATE TEMPORARY TABLESPACE TEMP TEMPFILE 
  'C:\APP\DANIELFRANCO\PRODUCT\21C\ORADATA\XE\XEPDB1\TEMP01.DBF' SIZE 212M AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M;


--
-- "DEFAULT"  (Profile) 
--
CREATE PROFILE "DEFAULT" LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION UNLIMITED
  CPU_PER_CALL UNLIMITED
  CONNECT_TIME UNLIMITED
  IDLE_TIME UNLIMITED
  LOGICAL_READS_PER_SESSION UNLIMITED
  LOGICAL_READS_PER_CALL UNLIMITED
  COMPOSITE_LIMIT UNLIMITED
  PRIVATE_SGA UNLIMITED
  FAILED_LOGIN_ATTEMPTS 10
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME UNLIMITED
  PASSWORD_REUSE_MAX UNLIMITED
  PASSWORD_LOCK_TIME 1
  PASSWORD_GRACE_TIME 7
  PASSWORD_VERIFY_FUNCTION NULL;


--
-- CONNECT  (Role) 
--
CREATE ROLE CONNECT NOT IDENTIFIED;

-- System privileges granted to CONNECT
GRANT CREATE SESSION TO CONNECT CONTAINER=ALL;
GRANT SET CONTAINER TO CONNECT CONTAINER=ALL;


--
-- DBA  (Role) 
--
CREATE ROLE DBA NOT IDENTIFIED;

-- Object privileges granted to DBA
GRANT EXECUTE ON ORDSYS.CARTRIDGE TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_HOME_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_INCIDENT_CORR_KEYS_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_INCIDENT_FILES_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_INCIDENT_INFO_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_INCIDENT_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ARGS_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ARG_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ECID_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_ERRID_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_SUPPL_ATTRS_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_SUPPL_ATTR_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.ADR_LOG_MSG_T TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.AS_REPLAY TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.CDB_XS_ACTIVE_SESSIONS TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.CDB_XS_SESSION_NS_ATTRIBUTES TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.CDB_XS_SESSION_ROLES TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.CDB_XS_SESSIONS TO DBA CONTAINER=ALL;
GRANT DELETE ON SYS.DBA_REGISTRY_SQLPATCH TO DBA CONTAINER=ALL;
GRANT INSERT ON SYS.DBA_REGISTRY_SQLPATCH TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.DBA_REGISTRY_SQLPATCH TO DBA CONTAINER=ALL;
GRANT UPDATE ON SYS.DBA_REGISTRY_SQLPATCH TO DBA CONTAINER=ALL;
GRANT DELETE ON SYS.DBA_REGISTRY_SQLPATCH_RU_INFO TO DBA CONTAINER=ALL;
GRANT INSERT ON SYS.DBA_REGISTRY_SQLPATCH_RU_INFO TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.DBA_REGISTRY_SQLPATCH_RU_INFO TO DBA CONTAINER=ALL;
GRANT UPDATE ON SYS.DBA_REGISTRY_SQLPATCH_RU_INFO TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.DBA_XS_ACTIVE_SESSIONS TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.DBA_XS_SESSION_NS_ATTRIBUTES TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.DBA_XS_SESSION_ROLES TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.DBA_XS_SESSIONS TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_ACTIVITY TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_ADBTASK_ADMIN TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_ADR TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_ADR_APP TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_APP_CONT TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_APP_CONT_ADMIN TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_APP_CONT_REPORT TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AUTO_INDEX TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AUTO_SQLSET TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AUTO_SQLTUNE TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_ADMIN TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AUTO_TASK_IMMEDIATE TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AWR_ANALYTICS TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AWRHUB TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AWRHUB_SERVER TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AWRHUB_SOURCE TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AWR_WAREHOUSE_SERVER TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_AWR_WAREHOUSE_SOURCE TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_CACHEUTIL TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_DLM TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_DNFS TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_FEATURE_USAGE_REPORT TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_FLASHBACK_ARCHIVE TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_FS TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_GSM_FIX TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_HANG_MANAGER TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_HCS_LOG TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_HM TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_ILM_ADMIN TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_INMEMORY_ADMIN TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_IR TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_LOGSTDBY TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_MANAGEMENT_BOOTSTRAP TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_MEMOPTIMIZE_ADMIN TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_MONITOR TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_NETWORK_ACL_ADMIN TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_PERF TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_RAT_MASK TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_REPLAYHUB TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_RESULT_CACHE TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_RESUMABLE TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_ROLLING TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SERVER_ALERT TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SERVICE TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SERVICE_CONST TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SERVICE_ERR TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SERVICE_PRVT TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_STORAGE_MAP TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_SWAT TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_TDB TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_TNS TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_UADV_ARR TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_UMF TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_UNDO_ADV TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_CAPTURE TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPLAY TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.DBMS_XS_PRINCIPALS TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.HM_SQLTK_INTERNAL TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.LOAD_UNDO_STAT TO DBA CONTAINER=ALL;
GRANT DELETE ON SYS.MAP_OBJECT TO DBA CONTAINER=ALL;
GRANT INSERT ON SYS.MAP_OBJECT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.MAP_OBJECT TO DBA CONTAINER=ALL;
GRANT UPDATE ON SYS.MAP_OBJECT TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.OJDS_CONTEXT TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.OUTLN_PKG TO DBA CONTAINER=ALL;
GRANT DELETE ON SYS.PDB_ARC_SKIP$ TO DBA CONTAINER=ALL;
GRANT INSERT ON SYS.PDB_ARC_SKIP$ TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.PDB_ARC_SKIP$ TO DBA CONTAINER=ALL;
GRANT UPDATE ON SYS.PDB_ARC_SKIP$ TO DBA CONTAINER=ALL;
GRANT DELETE ON SYS.PDB_REF_CATALOG$ TO DBA CONTAINER=ALL;
GRANT INSERT ON SYS.PDB_REF_CATALOG$ TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.PDB_REF_CATALOG$ TO DBA CONTAINER=ALL;
GRANT UPDATE ON SYS.PDB_REF_CATALOG$ TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.PRVT_DBMS_INMEMORY_ADMIN TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.RESET_UNDO_STAT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_ADR_CONTROL TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_ADR_CONTROL_AUX TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_ADR_INVALIDATION TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_ALERT_EXT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_AMS_XACTION TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USER_ACTION_DEF TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_ACT_PARAM_DEF TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_ACT_MAP TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DDE_USR_INC_TYPE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_CAPTURE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_CONFIG_ITEM TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_PATCH_CAPTURE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_PATCH_ITEM TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_PURGE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DFW_PURGE_ITEM TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DIAGV_INCIDENT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_DIR_EXT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_EM_DIAG_JOB TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_EM_TARGET_INFO TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_EM_USER_ACTIVITY TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_FDG_SET TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_FINDING TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_INFO TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_MESSAGE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_RECOMMENDATION TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_HM_RUN TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INCCKEY TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INCIDENT_FILE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_CONFIG TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_IMPT_DEF TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_INFO TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_PK_IMPTS TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_INC_METER_SUMMARY TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_CONFIGURATION TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_COPY_LOG TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_FILE_METADATA TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_FILE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_HISTORY TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PACKAGE_INCIDENT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PKG_UNPACK_HIST TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_PROGRESS_LOG TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_IPS_REMOTE_PACKAGE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_LOG_EXT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_PDB_PROBLEM TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_PDB_SPACE_MGMT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_PICKLEERR TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_PROBLEM TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_RELMD_EXT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_SWEEPERR TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_ACTINC TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_ACTPROB TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VADR_CONTROL TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VEM_USER_ACTLOG1 TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VHM_RUN TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIEW TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIEWCOL TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_INCCOUNT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_INCFCOUNT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VINCIDENT_FILE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VINC_METER_INFO TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_INC_METER_INFO_PROB TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_COPY_LOG TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_FILE_METADATA TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_FILE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_HISTORY TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_MAIN_INT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PACKAGE_SIZE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_FILE TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_CAND TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_INC_DTL1 TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VIPS_PKG_MAIN_PROBLEM TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_IPSPRBCNT1 TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_NFCINC TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VNOT_EXIST_INCIDENT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPDB_PROBLEM TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET_COUNT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_BUCKET1 TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_INT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM_LASTINC TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM1 TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VPROBLEM2 TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VSHOWCATVIEW TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VSHOWINCB_I TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_V_SWPERRCOUNT TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.V_$DIAG_VTEST_EXISTS TO DBA CONTAINER=ALL;
GRANT INSERT ON SYS.XSDB$SCHEMA_ACL TO DBA CONTAINER=ALL;
GRANT SELECT ON SYS.XSDB$SCHEMA_ACL TO DBA CONTAINER=ALL;
GRANT UPDATE ON SYS.XSDB$SCHEMA_ACL TO DBA CONTAINER=ALL;
GRANT EXECUTE ON SYS.XS_MTCACHE_INT TO DBA CONTAINER=ALL;
GRANT EXECUTE ON XDB.DBMS_CSX_ADMIN TO DBA CONTAINER=ALL;
GRANT EXECUTE ON XDB.DBMS_XDB_ADMIN TO DBA CONTAINER=ALL;
GRANT EXECUTE ON XDB.DBMS_XDBT TO DBA CONTAINER=ALL;
GRANT DELETE ON XDB.XDB$ACL TO DBA CONTAINER=ALL;
GRANT INSERT ON XDB.XDB$ACL TO DBA CONTAINER=ALL;
GRANT SELECT ON XDB.XDB$ACL TO DBA CONTAINER=ALL;
GRANT UPDATE ON XDB.XDB$ACL TO DBA CONTAINER=ALL;
GRANT DELETE ON XDB.XDB$CHECKOUTS TO DBA CONTAINER=ALL;
GRANT INSERT ON XDB.XDB$CHECKOUTS TO DBA CONTAINER=ALL;
GRANT SELECT ON XDB.XDB$CHECKOUTS TO DBA CONTAINER=ALL;
GRANT UPDATE ON XDB.XDB$CHECKOUTS TO DBA CONTAINER=ALL;
GRANT DELETE ON XDB.XDB$CONFIG TO DBA CONTAINER=ALL;
GRANT INSERT ON XDB.XDB$CONFIG TO DBA CONTAINER=ALL;
GRANT SELECT ON XDB.XDB$CONFIG TO DBA CONTAINER=ALL;
GRANT UPDATE ON XDB.XDB$CONFIG TO DBA CONTAINER=ALL;
GRANT DELETE ON XDB.XDB$D_LINK TO DBA CONTAINER=ALL;
GRANT INSERT ON XDB.XDB$D_LINK TO DBA CONTAINER=ALL;
GRANT SELECT ON XDB.XDB$D_LINK TO DBA CONTAINER=ALL;
GRANT UPDATE ON XDB.XDB$D_LINK TO DBA CONTAINER=ALL;
GRANT DELETE ON XDB.XDB$H_INDEX TO DBA CONTAINER=ALL;
GRANT INSERT ON XDB.XDB$H_INDEX TO DBA CONTAINER=ALL;
GRANT SELECT ON XDB.XDB$H_INDEX TO DBA CONTAINER=ALL;
GRANT UPDATE ON XDB.XDB$H_INDEX TO DBA CONTAINER=ALL;
GRANT DELETE ON XDB.XDB$H_LINK TO DBA CONTAINER=ALL;
GRANT INSERT ON XDB.XDB$H_LINK TO DBA CONTAINER=ALL;
GRANT SELECT ON XDB.XDB$H_LINK TO DBA CONTAINER=ALL;
GRANT UPDATE ON XDB.XDB$H_LINK TO DBA CONTAINER=ALL;
GRANT DELETE ON XDB.XDB$NLOCKS TO DBA CONTAINER=ALL;
GRANT INSERT ON XDB.XDB$NLOCKS TO DBA CONTAINER=ALL;
GRANT SELECT ON XDB.XDB$NLOCKS TO DBA CONTAINER=ALL;
GRANT UPDATE ON XDB.XDB$NLOCKS TO DBA CONTAINER=ALL;
GRANT DELETE ON XDB.XDB$RESCONFIG TO DBA CONTAINER=ALL;
GRANT INSERT ON XDB.XDB$RESCONFIG TO DBA CONTAINER=ALL;
GRANT SELECT ON XDB.XDB$RESCONFIG TO DBA CONTAINER=ALL;
GRANT UPDATE ON XDB.XDB$RESCONFIG TO DBA CONTAINER=ALL;
GRANT DELETE ON XDB.XDB$RESOURCE TO DBA CONTAINER=ALL;
GRANT INSERT ON XDB.XDB$RESOURCE TO DBA CONTAINER=ALL;
GRANT SELECT ON XDB.XDB$RESOURCE TO DBA CONTAINER=ALL;
GRANT UPDATE ON XDB.XDB$RESOURCE TO DBA CONTAINER=ALL;
GRANT DELETE ON XDB.X$PT23LVJDK4EL9LDAHTO4RRGH5N9U TO DBA;
GRANT INSERT ON XDB.X$PT23LVJDK4EL9LDAHTO4RRGH5N9U TO DBA;
GRANT SELECT ON XDB.X$PT23LVJDK4EL9LDAHTO4RRGH5N9U TO DBA;
GRANT UPDATE ON XDB.X$PT23LVJDK4EL9LDAHTO4RRGH5N9U TO DBA;

-- System privileges granted to DBA
GRANT ADMINISTER ANY SQL TUNING SET TO DBA CONTAINER=ALL;
GRANT ADMINISTER DATABASE TRIGGER TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RESOURCE_MANAGER_PRIVS.GRANT_SYSTEM_PRIVILEGE
  (GRANTEE_NAME   => 'DBA', 
   PRIVILEGE_NAME => 'ADMINISTER_RESOURCE_MANAGER',
   ADMIN_OPTION   => FALSE);
END;
/
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO DBA CONTAINER=ALL;
GRANT ADMINISTER SQL TUNING SET TO DBA CONTAINER=ALL;
GRANT ADVISOR TO DBA CONTAINER=ALL;
GRANT ALTER ANY ANALYTIC VIEW TO DBA CONTAINER=ALL;
GRANT ALTER ANY ASSEMBLY TO DBA CONTAINER=ALL;
GRANT ALTER ANY ATTRIBUTE DIMENSION TO DBA CONTAINER=ALL;
GRANT ALTER ANY CLUSTER TO DBA CONTAINER=ALL;
GRANT ALTER ANY CUBE TO DBA CONTAINER=ALL;
GRANT ALTER ANY CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT ALTER ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT ALTER ANY DIMENSION TO DBA CONTAINER=ALL;
GRANT ALTER ANY EDITION TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY HIERARCHY TO DBA CONTAINER=ALL;
GRANT ALTER ANY INDEX TO DBA CONTAINER=ALL;
GRANT ALTER ANY INDEXTYPE TO DBA CONTAINER=ALL;
GRANT ALTER ANY LIBRARY TO DBA CONTAINER=ALL;
GRANT ALTER ANY MATERIALIZED VIEW TO DBA CONTAINER=ALL;
GRANT ALTER ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT ALTER ANY MINING MODEL TO DBA CONTAINER=ALL;
GRANT ALTER ANY OPERATOR TO DBA CONTAINER=ALL;
GRANT ALTER ANY OUTLINE TO DBA CONTAINER=ALL;
GRANT ALTER ANY PROCEDURE TO DBA CONTAINER=ALL;
GRANT ALTER ANY ROLE TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.ALTER_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT ALTER ANY SEQUENCE TO DBA CONTAINER=ALL;
GRANT ALTER ANY SQL PROFILE TO DBA CONTAINER=ALL;
GRANT ALTER ANY SQL TRANSLATION PROFILE TO DBA CONTAINER=ALL;
GRANT ALTER ANY TABLE TO DBA CONTAINER=ALL;
GRANT ALTER ANY TRIGGER TO DBA CONTAINER=ALL;
GRANT ALTER ANY TYPE TO DBA CONTAINER=ALL;
GRANT ALTER DATABASE TO DBA CONTAINER=ALL;
GRANT ALTER LOCKDOWN PROFILE TO DBA CONTAINER=ALL;
GRANT ALTER PROFILE TO DBA CONTAINER=ALL;
GRANT ALTER RESOURCE COST TO DBA CONTAINER=ALL;
GRANT ALTER ROLLBACK SEGMENT TO DBA CONTAINER=ALL;
GRANT ALTER SESSION TO DBA CONTAINER=ALL;
GRANT ALTER SYSTEM TO DBA CONTAINER=ALL;
GRANT ALTER TABLESPACE TO DBA CONTAINER=ALL;
GRANT ALTER USER TO DBA CONTAINER=ALL;
GRANT ANALYZE ANY TO DBA CONTAINER=ALL;
GRANT ANALYZE ANY DICTIONARY TO DBA CONTAINER=ALL;
GRANT AUDIT ANY TO DBA CONTAINER=ALL;
GRANT AUDIT SYSTEM TO DBA CONTAINER=ALL;
GRANT BACKUP ANY TABLE TO DBA CONTAINER=ALL;
GRANT BECOME USER TO DBA CONTAINER=ALL;
GRANT CHANGE NOTIFICATION TO DBA CONTAINER=ALL;
GRANT COMMENT ANY MINING MODEL TO DBA CONTAINER=ALL;
GRANT COMMENT ANY TABLE TO DBA CONTAINER=ALL;
GRANT CREATE ANALYTIC VIEW TO DBA CONTAINER=ALL;
GRANT CREATE ANY ANALYTIC VIEW TO DBA CONTAINER=ALL;
GRANT CREATE ANY ASSEMBLY TO DBA CONTAINER=ALL;
GRANT CREATE ANY ATTRIBUTE DIMENSION TO DBA CONTAINER=ALL;
GRANT CREATE ANY CLUSTER TO DBA CONTAINER=ALL;
GRANT CREATE ANY CONTEXT TO DBA CONTAINER=ALL;
GRANT CREATE ANY CREDENTIAL TO DBA CONTAINER=ALL;
GRANT CREATE ANY CUBE TO DBA CONTAINER=ALL;
GRANT CREATE ANY CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT CREATE ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT CREATE ANY DIMENSION TO DBA CONTAINER=ALL;
GRANT CREATE ANY DIRECTORY TO DBA CONTAINER=ALL;
GRANT CREATE ANY EDITION TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY HIERARCHY TO DBA CONTAINER=ALL;
GRANT CREATE ANY INDEX TO DBA CONTAINER=ALL;
GRANT CREATE ANY INDEXTYPE TO DBA CONTAINER=ALL;
GRANT CREATE ANY JOB TO DBA CONTAINER=ALL;
GRANT CREATE ANY LIBRARY TO DBA CONTAINER=ALL;
GRANT CREATE ANY MATERIALIZED VIEW TO DBA CONTAINER=ALL;
GRANT CREATE ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT CREATE ANY MINING MODEL TO DBA CONTAINER=ALL;
GRANT CREATE ANY OPERATOR TO DBA CONTAINER=ALL;
GRANT CREATE ANY OUTLINE TO DBA CONTAINER=ALL;
GRANT CREATE ANY PROCEDURE TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE ANY SEQUENCE TO DBA CONTAINER=ALL;
GRANT CREATE ANY SQL PROFILE TO DBA CONTAINER=ALL;
GRANT CREATE ANY SQL TRANSLATION PROFILE TO DBA CONTAINER=ALL;
GRANT CREATE ANY SYNONYM TO DBA CONTAINER=ALL;
GRANT CREATE ANY TABLE TO DBA CONTAINER=ALL;
GRANT CREATE ANY TRIGGER TO DBA CONTAINER=ALL;
GRANT CREATE ANY TYPE TO DBA CONTAINER=ALL;
GRANT CREATE ANY VIEW TO DBA CONTAINER=ALL;
GRANT CREATE ASSEMBLY TO DBA CONTAINER=ALL;
GRANT CREATE ATTRIBUTE DIMENSION TO DBA CONTAINER=ALL;
GRANT CREATE CLUSTER TO DBA CONTAINER=ALL;
GRANT CREATE CREDENTIAL TO DBA CONTAINER=ALL;
GRANT CREATE CUBE TO DBA CONTAINER=ALL;
GRANT CREATE CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT CREATE CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT CREATE DATABASE LINK TO DBA CONTAINER=ALL;
GRANT CREATE DIMENSION TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_EVALUATION_CONTEXT_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE EXTERNAL JOB TO DBA CONTAINER=ALL;
GRANT CREATE HIERARCHY TO DBA CONTAINER=ALL;
GRANT CREATE INDEXTYPE TO DBA CONTAINER=ALL;
GRANT CREATE JOB TO DBA CONTAINER=ALL;
GRANT CREATE LIBRARY TO DBA CONTAINER=ALL;
GRANT CREATE LOCKDOWN PROFILE TO DBA CONTAINER=ALL;
GRANT CREATE LOGICAL PARTITION TRACKING TO DBA CONTAINER=ALL;
GRANT CREATE MATERIALIZED VIEW TO DBA CONTAINER=ALL;
GRANT CREATE MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT CREATE MINING MODEL TO DBA CONTAINER=ALL;
GRANT CREATE OPERATOR TO DBA CONTAINER=ALL;
GRANT CREATE PLUGGABLE DATABASE TO DBA CONTAINER=ALL;
GRANT CREATE PROCEDURE TO DBA CONTAINER=ALL;
GRANT CREATE PROFILE TO DBA CONTAINER=ALL;
GRANT CREATE PUBLIC DATABASE LINK TO DBA CONTAINER=ALL;
GRANT CREATE PUBLIC SYNONYM TO DBA CONTAINER=ALL;
GRANT CREATE ROLE TO DBA CONTAINER=ALL;
GRANT CREATE ROLLBACK SEGMENT TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.CREATE_RULE_SET_OBJ,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT CREATE SEQUENCE TO DBA CONTAINER=ALL;
GRANT CREATE SESSION TO DBA CONTAINER=ALL;
GRANT CREATE SQL TRANSLATION PROFILE TO DBA CONTAINER=ALL;
GRANT CREATE SYNONYM TO DBA CONTAINER=ALL;
GRANT CREATE TABLE TO DBA CONTAINER=ALL;
GRANT CREATE TABLESPACE TO DBA CONTAINER=ALL;
GRANT CREATE TRIGGER TO DBA CONTAINER=ALL;
GRANT CREATE TYPE TO DBA CONTAINER=ALL;
GRANT CREATE USER TO DBA CONTAINER=ALL;
GRANT CREATE VIEW TO DBA CONTAINER=ALL;
GRANT DEBUG ANY PROCEDURE TO DBA CONTAINER=ALL;
GRANT DEBUG CONNECT SESSION TO DBA CONTAINER=ALL;
GRANT DELETE ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT DELETE ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT DELETE ANY TABLE TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'DEQUEUE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => FALSE);
END;
/
GRANT DROP ANY ANALYTIC VIEW TO DBA CONTAINER=ALL;
GRANT DROP ANY ASSEMBLY TO DBA CONTAINER=ALL;
GRANT DROP ANY ATTRIBUTE DIMENSION TO DBA CONTAINER=ALL;
GRANT DROP ANY CLUSTER TO DBA CONTAINER=ALL;
GRANT DROP ANY CONTEXT TO DBA CONTAINER=ALL;
GRANT DROP ANY CUBE TO DBA CONTAINER=ALL;
GRANT DROP ANY CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT DROP ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT DROP ANY DIMENSION TO DBA CONTAINER=ALL;
GRANT DROP ANY DIRECTORY TO DBA CONTAINER=ALL;
GRANT DROP ANY EDITION TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY HIERARCHY TO DBA CONTAINER=ALL;
GRANT DROP ANY INDEX TO DBA CONTAINER=ALL;
GRANT DROP ANY INDEXTYPE TO DBA CONTAINER=ALL;
GRANT DROP ANY LIBRARY TO DBA CONTAINER=ALL;
GRANT DROP ANY MATERIALIZED VIEW TO DBA CONTAINER=ALL;
GRANT DROP ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT DROP ANY MINING MODEL TO DBA CONTAINER=ALL;
GRANT DROP ANY OPERATOR TO DBA CONTAINER=ALL;
GRANT DROP ANY OUTLINE TO DBA CONTAINER=ALL;
GRANT DROP ANY PROCEDURE TO DBA CONTAINER=ALL;
GRANT DROP ANY ROLE TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.DROP_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT DROP ANY SEQUENCE TO DBA CONTAINER=ALL;
GRANT DROP ANY SQL PROFILE TO DBA CONTAINER=ALL;
GRANT DROP ANY SQL TRANSLATION PROFILE TO DBA CONTAINER=ALL;
GRANT DROP ANY SYNONYM TO DBA CONTAINER=ALL;
GRANT DROP ANY TABLE TO DBA CONTAINER=ALL;
GRANT DROP ANY TRIGGER TO DBA CONTAINER=ALL;
GRANT DROP ANY TYPE TO DBA CONTAINER=ALL;
GRANT DROP ANY VIEW TO DBA CONTAINER=ALL;
GRANT DROP LOCKDOWN PROFILE TO DBA CONTAINER=ALL;
GRANT DROP LOGICAL PARTITION TRACKING TO DBA CONTAINER=ALL;
GRANT DROP PROFILE TO DBA CONTAINER=ALL;
GRANT DROP PUBLIC DATABASE LINK TO DBA CONTAINER=ALL;
GRANT DROP PUBLIC SYNONYM TO DBA CONTAINER=ALL;
GRANT DROP ROLLBACK SEGMENT TO DBA CONTAINER=ALL;
GRANT DROP TABLESPACE TO DBA CONTAINER=ALL;
GRANT DROP USER TO DBA CONTAINER=ALL;
GRANT EM EXPRESS CONNECT TO DBA CONTAINER=ALL;
GRANT ENABLE DIAGNOSTICS TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'ENQUEUE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY ASSEMBLY TO DBA CONTAINER=ALL;
GRANT EXECUTE ANY CLASS TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_EVALUATION_CONTEXT,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY INDEXTYPE TO DBA CONTAINER=ALL;
GRANT EXECUTE ANY LIBRARY TO DBA CONTAINER=ALL;
GRANT EXECUTE ANY OPERATOR TO DBA CONTAINER=ALL;
GRANT EXECUTE ANY PROCEDURE TO DBA CONTAINER=ALL;
GRANT EXECUTE ANY PROGRAM TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
BEGIN
SYS.DBMS_RULE_ADM.GRANT_SYSTEM_PRIVILEGE(
  PRIVILEGE    => SYS.DBMS_RULE_ADM.EXECUTE_ANY_RULE_SET,
  GRANTEE      => 'DBA',
  GRANT_OPTION => FALSE);
END;
/
GRANT EXECUTE ANY TYPE TO DBA CONTAINER=ALL;
GRANT EXECUTE ASSEMBLY TO DBA CONTAINER=ALL;
GRANT EXECUTE DYNAMIC MLE TO DBA CONTAINER=ALL;
GRANT EXPORT FULL DATABASE TO DBA CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO DBA CONTAINER=ALL;
GRANT FLASHBACK ARCHIVE ADMINISTER TO DBA CONTAINER=ALL;
GRANT FORCE ANY TRANSACTION TO DBA CONTAINER=ALL;
GRANT FORCE TRANSACTION TO DBA CONTAINER=ALL;
GRANT GLOBAL QUERY REWRITE TO DBA CONTAINER=ALL;
GRANT GRANT ANY OBJECT PRIVILEGE TO DBA CONTAINER=ALL;
GRANT GRANT ANY PRIVILEGE TO DBA CONTAINER=ALL;
GRANT GRANT ANY ROLE TO DBA CONTAINER=ALL;
GRANT IMPORT FULL DATABASE TO DBA CONTAINER=ALL;
GRANT INSERT ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT INSERT ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT INSERT ANY TABLE TO DBA CONTAINER=ALL;
GRANT LOCK ANY TABLE TO DBA CONTAINER=ALL;
GRANT LOGMINING TO DBA CONTAINER=ALL;
GRANT MANAGE ANY FILE GROUP TO DBA CONTAINER=ALL;
BEGIN
SYS.DBMS_AQADM.GRANT_SYSTEM_PRIVILEGE (
  PRIVILEGE    => 'MANAGE_ANY',
  GRANTEE      => 'DBA',
  ADMIN_OPTION => FALSE);
END;
/
GRANT MANAGE FILE GROUP TO DBA CONTAINER=ALL;
GRANT MANAGE SCHEDULER TO DBA CONTAINER=ALL;
GRANT MANAGE TABLESPACE TO DBA CONTAINER=ALL;
GRANT MERGE ANY VIEW TO DBA CONTAINER=ALL;
GRANT ON COMMIT REFRESH TO DBA CONTAINER=ALL;
GRANT QUERY REWRITE TO DBA CONTAINER=ALL;
GRANT READ ANY FILE GROUP TO DBA CONTAINER=ALL;
GRANT READ ANY TABLE TO DBA CONTAINER=ALL;
GRANT REDEFINE ANY TABLE TO DBA CONTAINER=ALL;
GRANT RESTRICTED SESSION TO DBA CONTAINER=ALL;
GRANT RESUMABLE TO DBA CONTAINER=ALL;
GRANT SELECT ANY CUBE TO DBA CONTAINER=ALL;
GRANT SELECT ANY CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT SELECT ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO DBA CONTAINER=ALL;
GRANT SELECT ANY MEASURE FOLDER TO DBA CONTAINER=ALL;
GRANT SELECT ANY MINING MODEL TO DBA CONTAINER=ALL;
GRANT SELECT ANY SEQUENCE TO DBA CONTAINER=ALL;
GRANT SELECT ANY TABLE TO DBA CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO DBA CONTAINER=ALL;
GRANT SET CONTAINER TO DBA CONTAINER=ALL;
GRANT UNDER ANY TABLE TO DBA CONTAINER=ALL;
GRANT UNDER ANY TYPE TO DBA CONTAINER=ALL;
GRANT UNDER ANY VIEW TO DBA CONTAINER=ALL;
GRANT UPDATE ANY CUBE TO DBA CONTAINER=ALL;
GRANT UPDATE ANY CUBE BUILD PROCESS TO DBA CONTAINER=ALL;
GRANT UPDATE ANY CUBE DIMENSION TO DBA CONTAINER=ALL;
GRANT UPDATE ANY TABLE TO DBA CONTAINER=ALL;
GRANT USE ANY JOB RESOURCE TO DBA CONTAINER=ALL;
GRANT USE ANY SQL TRANSLATION PROFILE TO DBA CONTAINER=ALL;

-- Roles granted to DBA
--
-- ACCHK_READ  (Role) 
--
GRANT ACCHK_READ TO DBA WITH ADMIN OPTION CONTAINER=ALL;
--
-- CAPTURE_ADMIN  (Role) 
--
GRANT CAPTURE_ADMIN TO DBA CONTAINER=ALL;
--
-- DATAPUMP_EXP_FULL_DATABASE  (Role) 
--
GRANT DATAPUMP_EXP_FULL_DATABASE TO DBA CONTAINER=ALL;
--
-- DATAPUMP_IMP_FULL_DATABASE  (Role) 
--
GRANT DATAPUMP_IMP_FULL_DATABASE TO DBA CONTAINER=ALL;
--
-- EM_EXPRESS_ALL  (Role) 
--
GRANT EM_EXPRESS_ALL TO DBA CONTAINER=ALL;
--
-- EXECUTE_CATALOG_ROLE  (Role) 
--
GRANT EXECUTE_CATALOG_ROLE TO DBA CONTAINER=ALL;
--
-- EXP_FULL_DATABASE  (Role) 
--
GRANT EXP_FULL_DATABASE TO DBA CONTAINER=ALL;
--
-- GATHER_SYSTEM_STATISTICS  (Role) 
--
GRANT GATHER_SYSTEM_STATISTICS TO DBA CONTAINER=ALL;
--
-- IMP_FULL_DATABASE  (Role) 
--
GRANT IMP_FULL_DATABASE TO DBA CONTAINER=ALL;
--
-- JAVA_ADMIN  (Role) 
--
GRANT JAVA_ADMIN TO DBA CONTAINER=ALL;
--
-- OLAP_DBA  (Role) 
--
GRANT OLAP_DBA TO DBA CONTAINER=ALL;
--
-- OLAP_XS_ADMIN  (Role) 
--
GRANT OLAP_XS_ADMIN TO DBA CONTAINER=ALL;
--
-- OPTIMIZER_PROCESSING_RATE  (Role) 
--
GRANT OPTIMIZER_PROCESSING_RATE TO DBA CONTAINER=ALL;
--
-- PPLB_ROLE  (Role) 
--
GRANT PPLB_ROLE TO DBA CONTAINER=ALL;
--
-- SCHEDULER_ADMIN  (Role) 
--
GRANT SCHEDULER_ADMIN TO DBA CONTAINER=ALL;
--
-- SELECT_CATALOG_ROLE  (Role) 
--
GRANT SELECT_CATALOG_ROLE TO DBA CONTAINER=ALL;
--
-- WM_ADMIN_ROLE  (Role) 
--
GRANT WM_ADMIN_ROLE TO DBA CONTAINER=ALL;
--
-- XDBADMIN  (Role) 
--
GRANT XDBADMIN TO DBA CONTAINER=ALL;
--
-- XDB_SET_INVOKER  (Role) 
--
GRANT XDB_SET_INVOKER TO DBA CONTAINER=ALL;


--
-- CONTABILIDAD  (User) 
--
CREATE USER CONTABILIDAD
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 2 Roles for CONTABILIDAD 
--
-- CONNECT  (Role) 
--
GRANT CONNECT TO CONTABILIDAD;
--
-- DBA  (Role) 
--
GRANT DBA TO CONTABILIDAD;
ALTER USER CONTABILIDAD DEFAULT ROLE ALL;

-- 1 System Privilege for CONTABILIDAD 
GRANT UNLIMITED TABLESPACE TO CONTABILIDAD;


--
-- SEC_CONCEPTOS_MOVIMIENTO  (Sequence) 
--
CREATE SEQUENCE CONTABILIDAD.SEC_CONCEPTOS_MOVIMIENTO
  START WITH 18
  MAXVALUE 99
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  GLOBAL;


--
-- SEC_CUENTAS  (Sequence) 
--
CREATE SEQUENCE CONTABILIDAD.SEC_CUENTAS
  START WITH 9
  MAXVALUE 99
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  GLOBAL;


--
-- SEC_MOVIMIENTOS  (Sequence) 
--
CREATE SEQUENCE CONTABILIDAD.SEC_MOVIMIENTOS
  START WITH 46
  MAXVALUE 9999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  GLOBAL;


--
-- SEC_TIPOS_MEDIOS_PAGO  (Sequence) 
--
CREATE SEQUENCE CONTABILIDAD.SEC_TIPOS_MEDIOS_PAGO
  START WITH 8
  MAXVALUE 99
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  GLOBAL;


--
-- SEC_TIPOS_MOVIMIENTOS  (Sequence) 
--
CREATE SEQUENCE CONTABILIDAD.SEC_TIPOS_MOVIMIENTOS
  START WITH 3
  MAXVALUE 99
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  NOKEEP
  GLOBAL;


--
-- CONCEPTOS_MOVIMIENTO  (Table) 
--
CREATE TABLE CONTABILIDAD.CONCEPTOS_MOVIMIENTO
(
  CODIGO           NUMBER(2),
  NOMBRE_CONCEPTO  VARCHAR2(100 BYTE),
  FECHA_CREACION   DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- TIPOS_MEDIO_PAGO  (Table) 
--
CREATE TABLE CONTABILIDAD.TIPOS_MEDIO_PAGO
(
  CODIGO          NUMBER(2),
  MEDIO_PAGO      VARCHAR2(100 BYTE),
  FECHA_CREACION  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- TIPOS_MOVIMIENTO  (Table) 
--
CREATE TABLE CONTABILIDAD.TIPOS_MOVIMIENTO
(
  CODIGO             NUMBER(2),
  NOMBRE_MOVIMIENTO  VARCHAR2(100 BYTE),
  FECHA_CREACION     DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- PK_CONCEPTOS_MOVIMIENTO  (Index) 
--
CREATE UNIQUE INDEX CONTABILIDAD.PK_CONCEPTOS_MOVIMIENTO ON CONTABILIDAD.CONCEPTOS_MOVIMIENTO
(CODIGO)
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--
-- PK_TIPOS_MEDIO_PAGO_CODIGO  (Index) 
--
CREATE UNIQUE INDEX CONTABILIDAD.PK_TIPOS_MEDIO_PAGO_CODIGO ON CONTABILIDAD.TIPOS_MEDIO_PAGO
(CODIGO)
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--
-- PK_TIPOS_MOVIMIENTO  (Index) 
--
CREATE UNIQUE INDEX CONTABILIDAD.PK_TIPOS_MOVIMIENTO ON CONTABILIDAD.TIPOS_MOVIMIENTO
(CODIGO)
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--
-- CUENTAS  (Table) 
--
CREATE TABLE CONTABILIDAD.CUENTAS
(
  CODIGO           NUMBER(2),
  NOMBRE_CUENTA    VARCHAR2(100 BYTE),
  TIPO_MEDIO_PAGO  NUMBER(2),
  FECHA_CREACION   DATE,
  VALOR            NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- MOVIMIENTOS  (Table) 
--
CREATE TABLE CONTABILIDAD.MOVIMIENTOS
(
  CODIGO              NUMBER(2),
  MOVIMIENTO          NUMBER(2),
  CONCEPTO            NUMBER(2),
  VALOR               NUMBER,
  CUENTA              NUMBER(2),
  DESCRIPCION         VARCHAR2(500 BYTE),
  FECHA_CREACION      DATE,
  FECHA_MODIFICACION  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;


--
-- PK_CUENTAS  (Index) 
--
CREATE UNIQUE INDEX CONTABILIDAD.PK_CUENTAS ON CONTABILIDAD.CUENTAS
(CODIGO, NOMBRE_CUENTA)
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--
-- PK_MOVIMIENTOS  (Index) 
--
CREATE UNIQUE INDEX CONTABILIDAD.PK_MOVIMIENTOS ON CONTABILIDAD.MOVIMIENTOS
(CODIGO, MOVIMIENTO, CONCEPTO)
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--
-- UQ_CUENTA  (Index) 
--
CREATE UNIQUE INDEX CONTABILIDAD.UQ_CUENTA ON CONTABILIDAD.CUENTAS
(CODIGO)
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--
-- VISTA_CONCEPTOS_VS_VALORES  (View) 
--
CREATE OR REPLACE FORCE VIEW CONTABILIDAD.VISTA_CONCEPTOS_VS_VALORES
(MOVIMIENTO, CONCEPTO, VALOR)
BEQUEATH DEFINER
AS 
SELECT T.NOMBRE_MOVIMIENTO MOVIMIENTO, C.NOMBRE_CONCEPTO CONCEPTO, NVL (SUM (M.VALOR), 0) VALOR
        FROM MOVIMIENTOS M, TIPOS_MOVIMIENTO T, CONCEPTOS_MOVIMIENTO C
       WHERE M.MOVIMIENTO = T.CODIGO
       AND M.CONCEPTO = C.CODIGO
    GROUP BY T.NOMBRE_MOVIMIENTO,C.NOMBRE_CONCEPTO;


--
-- VISTA_MOVIMIENTOS_VS_VALORES  (View) 
--
CREATE OR REPLACE FORCE VIEW CONTABILIDAD.VISTA_MOVIMIENTOS_VS_VALORES
(MOVIMIENTO, VALOR)
BEQUEATH DEFINER
AS 
SELECT T.NOMBRE_MOVIMIENTO MOVIMIENTO, NVL (SUM (M.VALOR), 0) VALOR
        FROM MOVIMIENTOS M, TIPOS_MOVIMIENTO T
       WHERE M.MOVIMIENTO = T.CODIGO
    GROUP BY T.NOMBRE_MOVIMIENTO;


--
-- TRI_ACTUALIZA_VALORES_CUENTAS  (Trigger) 
--
CREATE OR REPLACE TRIGGER CONTABILIDAD.tri_actualiza_valores_cuentas
    AFTER INSERT
    ON CONTABILIDAD.MOVIMIENTOS
    FOR EACH ROW
DECLARE
    n_numero_error    NUMBER;
    n_mensaje_error   VARCHAR2 (255);
BEGIN
    IF :new.movimiento = 1
    THEN
        UPDATE cuentas
           SET valor = valor + :new.valor
         WHERE codigo = :new.cuenta;
    ELSIF :new.movimiento = 2
    THEN
        UPDATE cuentas
           SET valor = valor - :new.valor
         WHERE codigo = :new.cuenta;
    END IF;
EXCEPTION
    WHEN OTHERS
    THEN
        n_numero_error := SQLCODE;
        n_mensaje_error := SQLERRM;
        RAISE_APPLICATION_ERROR (
            -20001,
               'Error actualizando valores de las cuentas: '
            || n_numero_error
            || ' mensaje error: '
            || n_mensaje_error);
END;
/


--
-- FUN_BALANCE  (Function) 
--
CREATE OR REPLACE FUNCTION CONTABILIDAD.fun_balance
    RETURN NUMBER
IS
    n_ingresos        NUMBER := 0;
    n_gastos          NUMBER := 0;
    n_numero_error    NUMBER;
    n_mensaje_error   VARCHAR2 (255);

    CURSOR cur_ingresos
    IS
        SELECT NVL (valor, 0) valor
          FROM vista_movimientos_vs_valores
         WHERE movimiento = 'INGRESO';

    CURSOR cur_gastos
    IS
        SELECT NVL (valor, 0) valor
          FROM vista_movimientos_vs_valores
         WHERE movimiento = 'GASTO';
BEGIN
    FOR indice_ingresos IN cur_ingresos
    LOOP
        n_ingresos := indice_ingresos.valor;
    END LOOP;

    FOR indice_gastos IN cur_gastos
    LOOP
        n_gastos := indice_gastos.valor;
    END LOOP;

    RETURN n_ingresos - n_gastos;
EXCEPTION
    WHEN OTHERS
    THEN
        n_numero_error := SQLCODE;
        n_mensaje_error := SQLERRM;
        RAISE_APPLICATION_ERROR (
            -20001,
               'Error al calcular balance funcion contabilidad.fun_balance, codigo error: '
            || n_numero_error
            || ' mensaje error: '
            || n_mensaje_error);
END;
/


-- 
-- Non Foreign Key Constraints for Table CONCEPTOS_MOVIMIENTO 
-- 
ALTER TABLE CONTABILIDAD.CONCEPTOS_MOVIMIENTO ADD (
  CONSTRAINT PK_CONCEPTOS_MOVIMIENTO
  PRIMARY KEY
  (CODIGO)
  USING INDEX CONTABILIDAD.PK_CONCEPTOS_MOVIMIENTO
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table TIPOS_MEDIO_PAGO 
-- 
ALTER TABLE CONTABILIDAD.TIPOS_MEDIO_PAGO ADD (
  CONSTRAINT PK_TIPOS_MEDIO_PAGO_CODIGO
  PRIMARY KEY
  (CODIGO)
  USING INDEX CONTABILIDAD.PK_TIPOS_MEDIO_PAGO_CODIGO
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table TIPOS_MOVIMIENTO 
-- 
ALTER TABLE CONTABILIDAD.TIPOS_MOVIMIENTO ADD (
  CONSTRAINT PK_TIPOS_MOVIMIENTO
  PRIMARY KEY
  (CODIGO)
  USING INDEX CONTABILIDAD.PK_TIPOS_MOVIMIENTO
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table CUENTAS 
-- 
ALTER TABLE CONTABILIDAD.CUENTAS ADD (
  CONSTRAINT PK_CUENTAS
  PRIMARY KEY
  (CODIGO, NOMBRE_CUENTA)
  USING INDEX CONTABILIDAD.PK_CUENTAS
  ENABLE VALIDATE);

ALTER TABLE CONTABILIDAD.CUENTAS ADD (
  CONSTRAINT UQ_CUENTA
  UNIQUE (CODIGO)
  USING INDEX CONTABILIDAD.UQ_CUENTA
  ENABLE VALIDATE);


-- 
-- Non Foreign Key Constraints for Table MOVIMIENTOS 
-- 
ALTER TABLE CONTABILIDAD.MOVIMIENTOS ADD (
  CONSTRAINT PK_MOVIMIENTOS
  PRIMARY KEY
  (CODIGO, MOVIMIENTO, CONCEPTO)
  USING INDEX CONTABILIDAD.PK_MOVIMIENTOS
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table CUENTAS 
-- 
ALTER TABLE CONTABILIDAD.CUENTAS ADD (
  CONSTRAINT FK_CUENTAS_TIPOS_MEDIO_PAGO 
  FOREIGN KEY (TIPO_MEDIO_PAGO) 
  REFERENCES CONTABILIDAD.TIPOS_MEDIO_PAGO (CODIGO)
  ENABLE VALIDATE);


-- 
-- Foreign Key Constraints for Table MOVIMIENTOS 
-- 
ALTER TABLE CONTABILIDAD.MOVIMIENTOS ADD (
  CONSTRAINT FK_MOVIMIENTOS_CONCEPTOS_MOVIMIENTO 
  FOREIGN KEY (CONCEPTO) 
  REFERENCES CONTABILIDAD.CONCEPTOS_MOVIMIENTO (CODIGO)
  ENABLE VALIDATE);

ALTER TABLE CONTABILIDAD.MOVIMIENTOS ADD (
  CONSTRAINT FK_MOVIMIENTOS_CUENTAS 
  FOREIGN KEY (CUENTA) 
  REFERENCES CONTABILIDAD.CUENTAS (CODIGO)
  ENABLE VALIDATE);