SET DEFINE OFF;
Insert into CONTABILIDAD.TIPOS_MEDIO_PAGO
   (CODIGO, MEDIO_PAGO, FECHA_CREACION)
 Values
   (5, 'AHORRO TARJETA', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.TIPOS_MEDIO_PAGO
   (CODIGO, MEDIO_PAGO, FECHA_CREACION)
 Values
   (6, 'AHORRO FONDO EMPLEADOS', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.TIPOS_MEDIO_PAGO
   (CODIGO, MEDIO_PAGO, FECHA_CREACION)
 Values
   (7, 'PLATAFORMAS DIGITALES', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.TIPOS_MEDIO_PAGO
   (CODIGO, MEDIO_PAGO, FECHA_CREACION)
 Values
   (3, 'TARJETA BONO', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.TIPOS_MEDIO_PAGO
   (CODIGO, MEDIO_PAGO, FECHA_CREACION)
 Values
   (4, 'TARJETA CREDITO', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.TIPOS_MEDIO_PAGO
   (CODIGO, MEDIO_PAGO, FECHA_CREACION)
 Values
   (1, 'EFECTIVO', TO_DATE('19/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.TIPOS_MEDIO_PAGO
   (CODIGO, MEDIO_PAGO, FECHA_CREACION)
 Values
   (2, 'TARJETA DEBITO', TO_DATE('19/03/2023', 'DD/MM/YYYY'));
COMMIT;
