SET DEFINE OFF;
Insert into CONTABILIDAD.TIPOS_MOVIMIENTO
   (CODIGO, NOMBRE_MOVIMIENTO, FECHA_CREACION)
 Values
   (1, 'INGRESO', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
Insert into CONTABILIDAD.TIPOS_MOVIMIENTO
   (CODIGO, NOMBRE_MOVIMIENTO, FECHA_CREACION)
 Values
   (2, 'GASTO', TO_DATE('20/03/2023', 'DD/MM/YYYY'));
COMMIT;
